# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 19:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20170228_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribeuser',
            name='posts',
        ),
        migrations.AddField(
            model_name='subscribeuser',
            name='followed_users',
            field=models.ManyToManyField(related_name='followed_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
