# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 19:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170228_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribeuser',
            name='followed_users',
            field=models.ManyToManyField(null=True, related_name='followed_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
