# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 20:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_auto_20170228_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribeuser',
            old_name='user',
            new_name='person',
        ),
        migrations.RemoveField(
            model_name='subscribeuser',
            name='followed_users',
        ),
        migrations.AddField(
            model_name='subscribeuser',
            name='followed_users',
            field=models.ManyToManyField(related_name='follows', to=settings.AUTH_USER_MODEL),
        ),
    ]
