# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 10:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_auto_20170228_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribeuserinfo',
            name='followed_users',
        ),
        migrations.AddField(
            model_name='subscribeuserinfo',
            name='followed_users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follows', to=settings.AUTH_USER_MODEL),
        ),
    ]
