# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 10:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_auto_20170301_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribeuserinfo',
            name='followed_users',
        ),
        migrations.AddField(
            model_name='subscribeuserinfo',
            name='followed_users',
            field=models.ManyToManyField(related_name='follows', to=settings.AUTH_USER_MODEL),
        ),
    ]
