# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 11:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_auto_20170301_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_read',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_read', to=settings.AUTH_USER_MODEL),
        ),
    ]
